name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Upload built artifact
      uses: actions/upload-artifact@v2
      with:
        name: linux-x64
        path: env-config
    
    - name: Copy the produced file to a S3 bucket
      uses: keithweaver/aws-s3-github-action@v0.1.2
      with:
        command: cp
        source: ./env-config
        destination: s3://iktech-public-dl/config/linux-x64/env-config
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
